# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: PR Build

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    paths-ignore:
      - "doc/**"
      - "docs/**"
      - "**.md"
  pull_request:
    paths-ignore:
      - "doc/**"
      - "docs/**"
      - "**.md"
  # manual trigger
  # https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch:

env:
  RUST_VERSION: stable

jobs:

  # run Comet test with full matrix of Java and Scala versions for the latest supported 3.5.x release
  linux-test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        java_version: [8, 11, 17]
        test-target: [rust, java]
        spark-version: ['3.5']
        scala-version: ['2.12', '2.13']
        is_push_event:
          - ${{ github.event_name == 'push' }}
        exclude: # exclude java 8 and 11 for pull_request event
          - java_version: 8
            is_push_event: false
          - java_version: 11
            is_push_event: false
      fail-fast: false
    name: ${{ matrix.os }}/java ${{ matrix.java_version }}-spark-${{matrix.spark-version}}-scala-${{matrix.scala-version}}/${{ matrix.test-target }}
    runs-on: ${{ matrix.os }}
    container:
      image: amd64/rust
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust & Java toolchain
        uses: ./.github/actions/setup-builder
        with:
          rust-version: ${{env.RUST_VERSION}}
          jdk-version: ${{ matrix.java_version }}
      - if: matrix.test-target == 'rust'
        name: Rust test steps
        uses: ./.github/actions/rust-test
      - if: matrix.test-target == 'java'
        name: Java test steps
        uses: ./.github/actions/java-test
        with:
          maven_opts: -Pspark-${{ matrix.spark-version }},scala-${{ matrix.scala-version }}
          # upload test reports only for java 17
          upload-test-reports: ${{ matrix.java_version == '17' }}

  # run Comet tests for older 3.5.x releases with one java and scala versions
  linux-test-35-minor-versions:
    strategy:
      matrix:
        os: [ubuntu-latest]
        java_version: [17]
        test-target: [java]
        spark-version: ['3.5']
        spark-patch-version: ['3.5.2', '3.5.3', '3.5.4']
        scala-version: ['2.12']
        is_push_event:
          - ${{ github.event_name == 'push' }}
      fail-fast: false
    name: ${{ matrix.os }}/java ${{ matrix.java_version }}-spark-${{matrix.spark-patch-version}}-scala-${{matrix.scala-version}}/${{ matrix.test-target }}
    runs-on: ${{ matrix.os }}
    container:
      image: amd64/rust
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust & Java toolchain
        uses: ./.github/actions/setup-builder
        with:
          rust-version: ${{env.RUST_VERSION}}
          jdk-version: ${{ matrix.java_version }}
      - if: matrix.test-target == 'rust'
        name: Rust test steps
        uses: ./.github/actions/rust-test
      - if: matrix.test-target == 'java'
        name: Java test steps
        uses: ./.github/actions/java-test
        with:
          maven_opts: "-Pspark-${{ matrix.spark-version }},scala-${{ matrix.scala-version }} -Dspark.version=${{ matrix.spark-patch-version }}"
          # upload test reports only for java 17
          upload-test-reports: ${{ matrix.java_version == '17' }}

  linux-test-native-datafusion-scan:
    strategy:
      matrix:
        os: [ubuntu-latest]
        scan_impl: ['native_datafusion', 'native_iceberg_compat']
        java_version: [17]
        test-target: [rust, java]
        spark-version: ['3.5']
        scala-version: ['2.12']
        is_push_event:
          - ${{ github.event_name == 'push' }}
      fail-fast: false
    name: ${{ matrix.os }}/java ${{ matrix.java_version }}-spark-${{matrix.spark-version}}-scala-${{matrix.scala-version}}/${{ matrix.test-target }}-${{ matrix.scan_impl }}
    runs-on: ${{ matrix.os }}
    env:
      COMET_PARQUET_SCAN_IMPL: ${{ matrix.scan_impl }}
    container:
      image: amd64/rust
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust & Java toolchain
        uses: ./.github/actions/setup-builder
        with:
          rust-version: ${{env.RUST_VERSION}}
          jdk-version: ${{ matrix.java_version }}
      - if: matrix.test-target == 'rust'
        name: Rust test steps
        uses: ./.github/actions/rust-test
      - if: matrix.test-target == 'java'
        name: Java test steps
        uses: ./.github/actions/java-test
        with:
          maven_opts: -Pspark-${{ matrix.spark-version }},scala-${{ matrix.scala-version }}
          # upload test reports only for java 17
          upload-test-reports: ${{ matrix.java_version == '17' }}

  linux-test-with-spark4_0:
    strategy:
      matrix:
        os: [ubuntu-latest]
        java_version: [17]
        test-target: [java]
        spark-version: ['4.0']
        is_push_event:
          - ${{ github.event_name == 'push' }}
      fail-fast: false
    name: ${{ matrix.os }}/java ${{ matrix.java_version }}-spark-${{matrix.spark-version}}/${{ matrix.test-target }}
    runs-on: ${{ matrix.os }}
    container:
      image: amd64/rust
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust & Java toolchain
        uses: ./.github/actions/setup-builder
        with:
          rust-version: ${{env.RUST_VERSION}}
          jdk-version: ${{ matrix.java_version }}
      - name: Java test steps
        uses: ./.github/actions/java-test
        with:
          maven_opts: -Pspark-${{ matrix.spark-version }}
          upload-test-reports: true

  linux-test-with-old-spark:
    strategy:
      matrix:
        os: [ubuntu-latest]
        java_version: [8, 11, 17]
        test-target: [java]
        spark-version: ['3.4']
        scala-version: ['2.12', '2.13']
      fail-fast: false
    name: ${{ matrix.os }}/java ${{ matrix.java_version }}-spark-${{matrix.spark-version}}-scala-${{matrix.scala-version}}/${{ matrix.test-target }}
    runs-on: ${{ matrix.os }}
    container:
      image: amd64/rust
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust & Java toolchain
        uses: ./.github/actions/setup-builder
        with:
          rust-version: ${{env.RUST_VERSION}}
          jdk-version: ${{ matrix.java_version }}
      - name: Java test steps
        uses: ./.github/actions/java-test
        with:
          maven_opts: -Pspark-${{ matrix.spark-version }},scala-${{ matrix.scala-version }}

  macos-test:
    strategy:
      matrix:
        os: [macos-13]
        java_version: [8, 11, 17]
        test-target: [rust, java]
        spark-version: ['3.4', '3.5']
        scala-version: ['2.12', '2.13']
        is_push_event:
          - ${{ github.event_name == 'push' }}
        exclude: # exclude java 8 and 11 for pull_request event
          - java_version: 8
            is_push_event: false
          - java_version: 11
            is_push_event: false
      fail-fast: false
    if: github.event_name == 'push'
    name: ${{ matrix.os }}/java ${{ matrix.java_version }}-spark-${{matrix.spark-version}}-scala-${{matrix.scala-version}}/${{ matrix.test-target }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust & Java toolchain
        uses: ./.github/actions/setup-macos-builder
        with:
          rust-version: ${{env.RUST_VERSION}}
          jdk-version: ${{ matrix.java_version }}
      - if: matrix.test-target == 'rust'
        name: Rust test steps
        uses: ./.github/actions/rust-test
      - if: matrix.test-target == 'java'
        name: Java test steps
        uses: ./.github/actions/java-test
        with:
          maven_opts: -Pspark-${{ matrix.spark-version }},scala-${{ matrix.scala-version }}

  macos-aarch64-test:
    strategy:
      matrix:
        java_version: [8, 11, 17]
        test-target: [rust, java]
        spark-version: ['3.4', '3.5']
        scala-version: ['2.12', '2.13']
        is_push_event:
          - ${{ github.event_name == 'push' }}
        exclude: # exclude java 8 and 11 for pull_request event
          - java_version: 8
            is_push_event: false
          - java_version: 11
            is_push_event: false
      fail-fast: false
    name: macos-14(Silicon)/java ${{ matrix.java_version }}-spark-${{matrix.spark-version}}-scala-${{matrix.scala-version}}/${{ matrix.test-target }}
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust & Java toolchain
        uses: ./.github/actions/setup-macos-builder
        with:
          rust-version: ${{env.RUST_VERSION}}
          jdk-version: ${{ matrix.java_version }}
          jdk-architecture: aarch64
          protoc-architecture: aarch_64
      - if: matrix.test-target == 'rust'
        name: Rust test steps
        uses: ./.github/actions/rust-test
      - if: matrix.test-target == 'java'
        name: Java test steps
        uses: ./.github/actions/java-test
        with:
          maven_opts: -Pspark-${{ matrix.spark-version }},scala-${{ matrix.scala-version }}

  macos-test-with-spark4_0:
    strategy:
      matrix:
        os: [macos-13]
        java_version: [17]
        test-target: [java]
        spark-version: ['4.0']
      fail-fast: false
    if: github.event_name == 'push'
    name: ${{ matrix.os }}/java ${{ matrix.java_version }}-spark-${{matrix.spark-version}}/${{ matrix.test-target }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust & Java toolchain
        uses: ./.github/actions/setup-macos-builder
        with:
          rust-version: ${{env.RUST_VERSION}}
          jdk-version: ${{ matrix.java_version }}
      - name: Java test steps
        uses: ./.github/actions/java-test
        with:
          maven_opts: -Pspark-${{ matrix.spark-version }}
          upload-test-reports: true

  macos-aarch64-test-with-spark4_0:
    strategy:
      matrix:
        java_version: [17]
        test-target: [java]
        spark-version: ['4.0']
      fail-fast: false
    name: macos-14(Silicon)/java ${{ matrix.java_version }}-spark-${{matrix.spark-version}}/${{ matrix.test-target }}
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust & Java toolchain
        uses: ./.github/actions/setup-macos-builder
        with:
          rust-version: ${{env.RUST_VERSION}}
          jdk-version: ${{ matrix.java_version }}
          jdk-architecture: aarch64
          protoc-architecture: aarch_64
      - name: Java test steps
        uses: ./.github/actions/java-test
        with:
          maven_opts: -Pspark-${{ matrix.spark-version }}
          upload-test-reports: true

  macos-aarch64-test-with-old-spark:
    strategy:
      matrix:
        java_version: [8, 17]
        test-target: [java]
        spark-version: ['3.4']
        scala-version: ['2.12', '2.13']
        exclude:
          - java_version: 8
      is_push_event:
        - ${{ github.event_name == 'push' }}
      exclude: # exclude java 8 for pull_request event
        - java_version: 8
          is_push_event: false
      fail-fast: false
    name: macos-14(Silicon)/java ${{ matrix.java_version }}-spark-${{matrix.spark-version}}-scala-${{matrix.scala-version}}/${{ matrix.test-target }}
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust & Java toolchain
        uses: ./.github/actions/setup-macos-builder
        with:
          rust-version: ${{env.RUST_VERSION}}
          jdk-version: ${{ matrix.java_version }}
          jdk-architecture: aarch64
          protoc-architecture: aarch_64
      - if: matrix.test-target == 'java'
        name: Java test steps
        uses: ./.github/actions/java-test
        with:
          maven_opts: -Pspark-${{ matrix.spark-version }},scala-${{ matrix.scala-version }}

